### ISSUE TITLE
Post Overlay 

### ISSUE THREAD

**Issue by austince** [robherley/cs146-js-autograder#2]
One of my students set the `class` name of the post-overlay `div` instead of setting the `id`. I know you mentioned that this is how the assignment should've been setup in the first place, but don't know if you told other people that. Should I give him full points for that?

**Comment by robherley** [comment]
Yea that was my mistake, it should really be a `class` instead of an `id`. In my opinion, you should probably give him full points.

**Comment by austince** [comment]
Cool, I'll do that!
